[package]
name = "ftdi-embedded-hal"
version = "0.1.0"
authors = ["Sergey Matyukevich <geomatsi@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.2"

[dependencies.ftdi]
git = "https://github.com/geomatsi/ftdi-rs"
