[package]
name = "ftdi-embedded-hal"
version = "0.1.0"
authors = ["Sergey Matyukevich <geomatsi@gmail.com>"]
edition = "2018"

[dependencies]
nb = "0.1.1"
rand = "0.6"
itertools = "0.7"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dependencies.ftdi]
git = "https://github.com/geomatsi/ftdi-rs"
branch = "wip-add-more-wrappers"

[dev-dependencies]
embedded-nrf24l01 = { git = "https://github.com/geomatsi/embedded-nrf24l01", branch = "update-deps" }
eeprom24x = "0.2.0"
